import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import useScript from '..//hooks/useScript'
import { useRouter } from 'next/router';


// Add SDK credentials
// REPLACE WITH YOUR PUBLIC KEY AVAILABLE IN: https://developers.mercadopago.com/panel
// const mercadopago = new MercadoPago('TEST-76ece74f-0345-4d52-a7ff-cd809fa384b4', {
//   locale: 'es-AR' // The most common are: 'pt-BR', 'es-AR' and 'en-US'
// });



export default function Home() {
  const [product,setProduct] = useState([{
    description: "Iphone 13",
    unit_price: Number(10),
    quantity: parseInt(1),
  }])
  const router = useRouter();

  // const { MercadoPago } = useScript(
  //   "https://sdk.mercadopago.com/js/v2",
  //   "MercadoPago"
  // );
  

  const handleBuy = (product) => {

    fetch('http://localhost:3000/api/create_preference', {
      method: 'POST', // *GET, POST, PUT, DELETE, etc.
      headers: {
        'Content-Type': 'application/json'
        // 'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: JSON.stringify(product) // body data type must match "Content-Type" header
    }).then(function(response) {
      console.log(response)
      return response.json();
    })
    .then(function(preference) {
      console.log("PREFERENCE ID DE PAGO DE MP ---->", preference.id);
      console.log("RUTA DE REDIRECCION AL PAGO DE MP ----->",preference.redirect)

      //REDIRECCION A CHECKOUTPRO
      router.replace(preference.redirect);
    }).catch(err => {
      //DISABLED BUTTON
      console.log("ERR",err);
    });
    
  }


  // // Create preference when click on checkout button
  // function createCheckoutButton(preferenceId) {
  //   // Initialize the checkout
  //   mercadopago.checkout({
  //     preference: {
  //       id: preferenceId
  //     },
  //     render: {
  //       container: '#buttonCheckout', // Class name where the payment button will be displayed
  //       label: 'Pagar', // Change the payment button text (optional)
  //     }
  //   });
  // }



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="Check out pro Prueba" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://sdk.mercadopago.com/js/v2"></script> */}

      </Head>

      
      <div className={styles.productContainer}>
        <Image width={200} height={200} src="/iphone.jpg" alt='itemcompra'/>
        <div className={styles.productDescription}>
          <h3>{product[0].title}</h3>
          <p>Price: ${product[0].unit_price}</p>
          <p>Quantity: {product[0].quantity}</p>
        </div>
        <button className={styles.buttonCheckout} onClick={() => handleBuy(product)}>Comprar por MP</button>
      </div>



    </div>
  )
}
